### ISSUE TITLE
Update addons, for games like WoW

### ISSUE THREAD

**Issue by SteveEbey73742** [hzeroo/twitch-desktop#10]
@hzeroo How hard would it be to implement addon updating?  Blizzard has released classic wow, and I would love to have an automatic solution to updating my game addons, rather than having to download them manually. when twitch merged with curse, the client never worked under wine, so was hoping for a native linux solution.

**Comment by hryuk** [comment]
I don't know how hard would it be, i suspect it might not take too much time despite of not knowing too much about WOW addon ecosystem. The problem here is that one of the main objetives i wanted to address with this project appart from linux support is compatibility with old or low-powered systems, keeping the app as small and fast as I can archive, even it being an electron app, so adding extra features not directly tied to twitch viewer is out of scope for the project.

That being said, i'm not against a fork for a more feature-rich project, or even a plugin system built into the project that could provide extra features. I will focus my limited time on 'basic' features currently still not implemented such as VOD's, but i would consider any PR or proposal about this topic if there is interest on this being implemented.
